spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/aksjeradar}
    username: ${DB_USER:appuser}
    password: ${DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: ${PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
